# Site settings
title: ACEM corp
email: acemcorp@acemcorp.com
description: > # this means to ignore newlines until "baseurl:"
  Aquatic Consultancy for Engineering & Management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +1 571 918 1013
copyright: ACEM Corp

# API settings
google_api_key:

# Build settings
markdown: kramdown
